### ISSUE TITLE
Is Entity Inheritance Possible with a single Repository?

### ISSUE THREAD

**Issue by pluttrell** [derjust/spring-data-dynamodb#126]
Is there a way to use a single `Repository` to produce multiple types that inherit from an abstract class if they are stored in a single table? For example if `Cat` and `Dog` both extend `Animal` and are both stored in a table called Animals? The single `Repository` would need instantiate the proper type when returning instances.

JPA supports this with `@Inheritance(strategy = SINGLE_TABLE)`, `@DiscriminatorColumn` and `@DiscriminatorValue` as shown here: https://saurabh1.com/2015/04/14/inheritance/. I've tried this example but it fails with this error:

```
Caused by: java.lang.InstantiationException: example.Animal
	at java.lang.Class.newInstance(Class.java:427)
	at com.amazonaws.services.dynamodbv2.datamodeling.StandardBeanProperties$DeclaringReflect.newInstance(StandardBeanProperties.java:183)
	... 34 more
Caused by: java.lang.NoSuchMethodException: example.Animal.<init>()
```

**Comment by derjust** [comment]
Right now it does not support this - the mapping is done by `DynamoDBMapper` and it does not support this; and it does not support passing in an instance object to get filled.

I can see how this get implemented but will be quite expensive:
* The load of an instance would require 2 loads (one for the key and the type, one for the real thing)
** And I don't know if the mapper meta data cache support that (same table, different columns/type)
* Scan operations would be hard because you could only serach for animal - or pass the type in for each of the `find` methods - as the Repository would be typed to the super type.
** Worth checking how the JPA guys do it :)

So a lot of work, theoretically possible (and therefore quite a long way down the road)

**Comment by pluttrell** [comment]
I discovered that [others](https://github.com/aws/aws-sdk-java/issues/832) are looking for this as well and there's an open [PR](https://github.com/aws/aws-sdk-java/pull/1229) from about 7 months ago.

**Comment by derjust** [comment]
Thanks for digging that up.
Worth a shot to build a custom AWS SDK and Test it out

Thanks!



On Feb 2, 2018, at 00:57, Peter Luttrell <notifications@github.com<mailto:notifications@github.com>> wrote:


I discovered that others<https://github.com/aws/aws-sdk-java/issues/832> are looking for this as well and there's an open PR<https://github.com/aws/aws-sdk-java/pull/1229> from about 7 months ago.

**Comment by snakeru** [comment]
@derjust this could be implemented much cheaper if we store the deserialization hint as the prefix of the search key. See https://github.com/aws/aws-sdk-java/issues/1867
