### ISSUE TITLE
Spring Boot - MySQL and DynamoDB together

### ISSUE THREAD

**Issue by Tutankhamon** [derjust/spring-data-dynamodb#127]
## Expected Behavior
Normal startup. MySQL repos work with MySQL entities (and they actually do), DynamoDB repos work with DynamoDB entities.

## Actual Behavior
Spring Boot app does not start due to an error with @DynamoDBTable entity. It seems autoconfiguration does not work for DynamoDB. Should I renounce to automatic JPA configuration, maybe?

## Steps to Reproduce the Problem

  1. Use "spring-boot-starter-data-jpa" within dependecies
  1. Create some repos for MySQL entities
  1. Create a DynamoDBTable entity (in the same "model" folder of MySQL entities (see 'A')
  1. Create DynamoDBConfig class (see 'B')
  1. Create DynamoDB Crude Repository (see 'C')
  1. Start the app

A:
```java
package com.somotic.scm.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.persistence.Id;
import java.io.Serializable;
import java.util.Date;

@DynamoDBTable(tableName = "DeviceValue")
public class DeviceValue implements Serializable {
    @Id
    private DeviceValueKey key;

    @DynamoDBAttribute(attributeName = "Value")
    private double value;

    @DynamoDBAttribute(attributeName = "LastChange")
    private Date lastChange;



    private DeviceValue(DeviceValueKey key, double value, Date lastChange) {
        this.key = key;
        this.value = value;
        this.lastChange = lastChange;
    }

    public DeviceValue(Long contextID, String tag, double value, Date lastChange) {
        this(new DeviceValueKey(contextID, tag), value, lastChange);
    }

    public DeviceValue() {}


    @DynamoDBHashKey(attributeName = "ContextID")
    public Long getContextID() {
        return (key != null) ? key.getContextID() : null;
    }

    public void setContextID(Long contextID) {
        if (key == null) {
            key = new DeviceValueKey();
        }
        key.setContextID(contextID);
    }

    @DynamoDBRangeKey(attributeName = "TAG")
    public String getTag() {
        return (key != null) ? key.getTag() : null;
    }

    public void setTag(String tag) {
        if (key == null) {
            key = new DeviceValueKey();
        }
        key.setTag(tag);
    }

    public double getValue() {
        return value;
    }

    public void setValue(double value) {
        this.value = value;
    }

    public Date getLastChange() {
        return lastChange;
    }

    public void setLastChange(Date lastChange) {
        this.lastChange = lastChange;
    }
}
```

B:
```java
package com.somotic.scm.controller;

import com.amazonaws.auth.*;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import org.socialsignin.spring.data.dynamodb.repository.config.EnableDynamoDBRepositories;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@EnableDynamoDBRepositories(value = "com.somotic.scm.repo.nosql")
public class DynamoDBConfig {
    @Value("${amazon.aws.accesskey}")
    private String amazonAWSAccessKey;

    @Value("${amazon.aws.secretkey}")
    private String amazonAWSSecretKey;
    
    public AWSCredentialsProvider amazonAWSCredentialsProvider() {
        return new AWSStaticCredentialsProvider(amazonAWSCredentials());
    }

    @Bean
    public AWSCredentials amazonAWSCredentials() {
        return new BasicAWSCredentials(amazonAWSAccessKey, amazonAWSSecretKey);
    }

    @Bean
    public AmazonDynamoDB amazonDynamoDB() {
        return AmazonDynamoDBClientBuilder.standard()
                .withCredentials(amazonAWSCredentialsProvider())
                .withRegion(Regions.EU_CENTRAL_1)
                .build();
    }
}
```

C:
```java
package com.somotic.scm.repo.nosql;

import com.somotic.scm.model.DeviceValue;
import com.somotic.scm.model.DeviceValueKey;
import org.socialsignin.spring.data.dynamodb.repository.EnableScan;
import org.springframework.data.repository.CrudRepository;

@EnableScan
public interface DeviceValueRepository extends CrudRepository<DeviceValue, DeviceValueKey> {

}
```

## Specifications
  
  - Spring Data DynamoDB Version: RELEASE
  - Spring Data Version: RELEASE
  - AWS SDK Version: RELEASE
  - Java Version: 1.8
  - Platform Details: Ubuntu Mate

**Comment by derjust** [comment]
Root cause

```
Caused by: java.lang.IllegalArgumentException: Not a managed type: class hello.DeviceValue
	at org.hibernate.jpa.internal.metamodel.MetamodelImpl.managedType(MetamodelImpl.java:210) ~[hibernate-entitymanager-5.0.12.Final.jar:5.0.12.Final]
	at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation.<init>(JpaMetamodelEntityInformation.java:70) ~[spring-data-jpa-1.11.9.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaEntityInformationSupport.getEntityInformation(JpaEntityInformationSupport.java:68) ~[spring-data-jpa-1.11.9.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getEntityInformation(JpaRepositoryFactory.java:173) ~[spring-data-jpa-1.11.9.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:106) ~[spring-data-jpa-1.11.9.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:88) ~[spring-data-jpa-1.11.9.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:200) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:277) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:263) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:101) ~[spring-data-jpa-1.11.9.RELEASE.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
```

**Comment by derjust** [comment]
Ok here we go - both repository factories try to register all repository interfaces with them -which doesn't work very well. Especially because spring-boot does a lot of auto-magic behind the curtain via the implicit existing `@EnableJpaRepositories`.

The solution is to tell JPA and DynamoDB which repositories they are responsibility for (which then also drives which entities are registered):

For Spring-Boot:

```java
@SpringBootApplication
@EnableJpaRepositories(
		includeFilters = {
		@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, classes = {
				CustomerRepository.class}
		)}
)
@EnableDynamoDBRepositories(
		includeFilters = {
				@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, classes = {
						DeviceValueRepository.class}
				)
		})
public class Application {
```

Same for a configuration class:
```java
@Configuration
@EnableJpaRepositories(includeFilters = {
//or use basePackages or excludeFilters
	@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, classes = {CustomerRepository.class})
})
@EnableDynamoDBRepositories(includeFilters = {
//or use basePackages or excludeFilters
	@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, classes = {DeviceValueRepository.class})
})
public class AppConfig {
```

**Comment by derjust** [comment]
Added wiki page https://github.com/derjust/spring-data-dynamodb/wiki/Multi-Repository-configuration

**Comment by derjust** [comment]
Does this work for you @Tutankhamon ?

**Comment by Tutankhamon** [comment]
Well, first of all thanks for your extremely quick answer. Second, it does not work but, this time, the problem is more "addressable" at least (I guess). I've tried your solution and a more "concise" version:
```
@SpringBootApplication
@EnableJpaRepositories(basePackages = "com.somotic.scm.repo.sql")
@EnableDynamoDBRepositories(basePackages = "com.somotic.scm.repo.nosql")
public class ScmApplication {

	public static void main(String[] args) {
		SpringApplication.run(ScmApplication.class, args);
	}
}
```

With the same result (just the meaningful section):
```
Caused by: java.lang.NoClassDefFoundError: org/springframework/data/querydsl/QuerydslUtils
	at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory.isQueryDslRepository(DynamoDBRepositoryFactory.java:84) ~[spring-data-dynamodb-5.0.1.jar:na]
	at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory.getRepositoryBaseClass(DynamoDBRepositoryFactory.java:77) ~[spring-data-dynamodb-5.0.1.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepositoryInformation(RepositoryFactorySupport.java:272) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:196) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:277) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:263) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 29 common frames omitted
```

I googled for a solution and have tried to import spring-data-commons but doing that led me to compilation errors: every embedded "magic" CrudRepository method seem to be unrecognized.

```
Error:(35, 40) java: cannot find symbol
  symbol:   method findOne(java.lang.Long)
  location: variable contextRepository of type com.somotic.scm.repo.sql.ContextRepository
```

**Comment by derjust** [comment]
This `NoClassDefFoundError` for `QuerydslUtils` happens if `spring-data` and `spring-data-dynamodb` don't match.
Please see which versions are used (via `mvn dependency:tree |grep spring-data` or similar).
My guess is that the classpath has a `spring-data` < `2.0` and a `spring-data-dynamodb` >= `5.0` (and with the fix for #122 going forward the version logging will be even more helpful)

The compatibility matrix as of today is as following:
 
|`spring-data-dynamodb` version  | Spring Boot compatibility      |Spring Framework compatibility  | Spring Data compatibility |
| ------------------------------- | ------------------------------ | ------------------------------ | ------------------------- |
| 4.4.x                           | => 1.4.0 < 2.0                 | >= 4.3 && < 5.0                | Hopper-SR2                |
| 4.5.x                           | => 1.4.0 < 2.0                 | >= 4.3 && < 5.0                | Ingalls                   |
| 5.0.x                           | => 2.0                         | >= 5.0                         | Kay-SR1                   |

**Comment by Tutankhamon** [comment]
Thanks @derjust! You've just made my day! However, I've just upgraded the spring-boot-starter-parent version to 2.0.0.RC1 (enabling spring-milestone repository) and everything has settled.

**Comment by jackmahoney** [comment]
For others, this worked for me (kotlin):

```kotlin
@SpringBootApplication
@EnableJpaRepositories(excludeFilters = [
  ComponentScan.Filter(type = FilterType.ANNOTATION, classes = [EnableScan::class])
])
```
