### ISSUE TITLE
[Spring Boot] Repository.save() exception

### ISSUE THREAD

**Issue by Tutankhamon** [derjust/spring-data-dynamodb#135]
Hello Again. After some time passed to get MySQL and DynamoDB coexisting in the same Spring Boot app, I thought that everything had to work. But it is not so... Now I'm trying to **SAVE** the same business object I successful read, **with no success**.

Here some code of mine:

BusinessObject
```java
package com.somotic.scm.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.data.annotation.Id;

import java.io.Serializable;
import java.util.Date;

@DynamoDBTable(tableName = "DeviceValue")
public class DeviceValue implements Serializable {
    @Id
    private DeviceValueKey key;

    @DynamoDBAttribute(attributeName = "Value")
    private int value;

    @DynamoDBAttribute(attributeName = "LastChange")
    private Date lastChange;

    public DeviceValue(DeviceValueKey key, int value, Date lastChange) {
        this.key = key;
        this.value = value;
        this.lastChange = lastChange;
    }

    public DeviceValue(Long contextID, String tag, int value, Date lastChange) {
        this(new DeviceValueKey(contextID, tag), value, lastChange);
    }

    public DeviceValue() {}

    @DynamoDBHashKey(attributeName = "ContextID")
    public Long getContextID() {
        return (key != null) ? key.getContextID() : null;
    }

    public void setContextID(Long contextID) {
        if (key == null) {
            key = new DeviceValueKey();
        }
        key.setContextID(contextID);
    }

    @DynamoDBRangeKey(attributeName = "TAG")
    public String getTag() {
        return (key != null) ? key.getTag() : null;
    }

    public void setTag(String tag) {
        if (key == null) {
            key = new DeviceValueKey();
        }
        key.setTag(tag);
    }

    public DeviceValueKey getKey() {
        return key;
    }

    public void setKey(DeviceValueKey key) {
        this.key = key;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    public Date getLastChange() {
        return lastChange;
    }

    public void setLastChange(Date lastChange) {
        this.lastChange = lastChange;
    }
}
```
The composite key of the business object above:
```java
package com.somotic.scm.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

import java.io.Serializable;

public class DeviceValueKey implements Serializable {
    private Long contextID;
    private String tag;

    DeviceValueKey() {}

    public DeviceValueKey(Long contextID, String tag) {
        this.contextID = contextID;
        this.tag =  tag;
    }

    @DynamoDBHashKey
    public Long getContextID() {
        return contextID;
    }

    public void setContextID(Long contextID) {
        this.contextID = contextID;
    }

    @DynamoDBRangeKey
    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }
}
```
The repository:
```java
package com.somotic.scm.repo.nosql;

import com.somotic.scm.model.DeviceValue;
import com.somotic.scm.model.DeviceValueKey;
import org.springframework.data.repository.CrudRepository;

public interface DeviceValueRepository extends CrudRepository<DeviceValue, DeviceValueKey> {

}
```
The calling code:
```java
public void handleDelivery(String consumerTag, Envelope envelope, AMQP.BasicProperties properties, byte[] body) throws IOException {
            String message = new String(body, "UTF-8");
            // State message management "<TAG>:<VALUE>"
            String[] splitted = message.split(":");
            String tag = splitted[0];
            int value = Integer.parseInt(splitted[1]);
            
            // NoSQL Update
            Optional<DeviceValue> deviceValueOptional = deviceValueRepository.findById(new DeviceValueKey(contextId, tag));
            DeviceValue deviceValue = null;
            if (deviceValueOptional.isPresent()) {
                deviceValue = deviceValueOptional.get();
                deviceValue.setValue(value);
                deviceValue.setLastChange(new Date());
            } else {
                deviceValue = new DeviceValue(new DeviceValueKey(contextId, tag), value, new Date());
            }
            deviceValueRepository.save(deviceValue);

            // Notify listeners
        }
```
And last but not least, The Exception:
```
com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: not supported; requires @DynamoDBTyped or @DynamoDBTypeConverted
	at com.amazonaws.services.dynamodbv2.datamodeling.StandardModelFactories$Rules$NotSupported.set(StandardModelFactories.java:664) ~[aws-java-sdk-dynamodb-1.11.232.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.StandardModelFactories$Rules$NotSupported.set(StandardModelFactories.java:650) ~[aws-java-sdk-dynamodb-1.11.232.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.StandardModelFactories$AbstractRule.convert(StandardModelFactories.java:709) ~[aws-java-sdk-dynamodb-1.11.232.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.StandardModelFactories$AbstractRule.convert(StandardModelFactories.java:691) ~[aws-java-sdk-dynamodb-1.11.232.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.convert(DynamoDBMapperFieldModel.java:138) ~[aws-java-sdk-dynamodb-1.11.232.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.execute(DynamoDBMapper.java:721) ~[aws-java-sdk-dynamodb-1.11.232.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.save(DynamoDBMapper.java:623) ~[aws-java-sdk-dynamodb-1.11.232.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.save(AbstractDynamoDBMapper.java:123) ~[aws-java-sdk-dynamodb-1.11.232.jar:na]
	at org.socialsignin.spring.data.dynamodb.core.DynamoDBTemplate.save(DynamoDBTemplate.java:141) ~[spring-data-dynamodb-5.0.1.jar:na]
	at org.socialsignin.spring.data.dynamodb.repository.support.SimpleDynamoDBCrudRepository.save(SimpleDynamoDBCrudRepository.java:121) ~[spring-data-dynamodb-5.0.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:377) ~[spring-data-commons-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200) ~[spring-data-commons-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:629) ~[spring-data-commons-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:593) ~[spring-data-commons-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578) ~[spring-data-commons-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at com.sun.proxy.$Proxy115.save(Unknown Source) ~[na:na]
	at com.somotic.scm.mq.MQContext$MQListener.handleDelivery(MQContext.java:87) ~[classes/:na]
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149) ~[amqp-client-5.1.2.jar:5.1.2]
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100) [amqp-client-5.1.2.jar:5.1.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
```
I repeat: **I have absolutely no problem when READING from DynamoDB (*repository.findById()*)**. This problem is raised only when I try to save something. Could it be the composite key? Initially, I thought it was a problem related to the "java.util.Date lastChange" field, but the same exception is raised when I add *DynamoDBIgnore Annotation* to that field. Any clue? thanks in advance.

**Comment by Tutankhamon** [comment]
Sorry, I'm a m***n. This "fake issue" has been solved reading this:

> In your entity class, instead of the hash key field and range key field, you have a field that is an instance of the specialized key class mentioned above. You must annotate that field with Spring's @Id annotation, **but do not provide a getter or setter**.

**Comment by derjust** [comment]
Thanks for the feedback. will clarify in the wiki

**Comment by derjust** [comment]
Updated [wiki](https://github.com/derjust/spring-data-dynamodb/wiki/Use-Hash-Range-keys).
