### ISSUE TITLE
IllegalStateException when using both hash and range key

### ISSUE THREAD

**Issue by arkigabor** [derjust/spring-data-dynamodb#164]
## Expected Behavior

Hash and range keys should be able to work within a single object.

## Actual Behavior

When providing both hash and range keys, the initialization fails with: `java.lang.IllegalStateException: No field found for annotation interface org.springframework.data.annotation.Id`!

## Steps to Reproduce the Problem

  1.  Create a model, for example:
```java
@DynamoDBTable(tableName = "test")
public class Example {
    private String hashkey;
    private String rangekey;
    private String value;

    @DynamoDBHashKey
    public String getHashkey() {
        return hashkey;
    }

    @DynamoDBRangeKey
    public String getRangekey() {
        return rangekey;
    }

    @DynamoDBAttribute
    public String getValue() {
        return value;
    }
}
```
  2. Create a repository.
  3. Try to initialize.

## Specifications
  
  - Spring Data DynamoDB Version: 5.0.2
  - Spring Data Version: Kay-SR7 (tested with all versions between SR1-7)
  - AWS SDK Version: 1.11.64
  - Java Version: Java 8
  - Platform Details: Spring Boot 2.0.2

Stacktrace:
```
Caused by: java.lang.IllegalArgumentException: Couldn't find field with annotation interface org.springframework.data.annotation.Id!
	at org.springframework.data.repository.core.support.ReflectionEntityInformation.<init>(ReflectionEntityInformation.java:70) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBIdIsHashAndRangeKeyEntityInformationImpl.<init>(DynamoDBIdIsHashAndRangeKeyEntityInformationImpl.java:44) ~[spring-data-dynamodb-5.0.2.jar:5.0.2]
	at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBEntityMetadataSupport.getEntityInformation(DynamoDBEntityMetadataSupport.java:127) ~[spring-data-dynamodb-5.0.2.jar:5.0.2]
	at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory.getEntityInformation(DynamoDBRepositoryFactory.java:105) ~[spring-data-dynamodb-5.0.2.jar:5.0.2]
	at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory.getDynamoDBRepository(DynamoDBRepositoryFactory.java:125) ~[spring-data-dynamodb-5.0.2.jar:5.0.2]
	at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory.getTargetRepository(DynamoDBRepositoryFactory.java:147) ~[spring-data-dynamodb-5.0.2.jar:5.0.2]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:298) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$3(RepositoryFactoryBeanSupport.java:287) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:141) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.util.Lazy.get(Lazy.java:63) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:290) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1765) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	... 29 common frames omitted
Caused by: java.lang.IllegalStateException: No field found for annotation interface org.springframework.data.annotation.Id!
	at org.springframework.data.util.AnnotationDetectionFieldCallback.getRequiredField(AnnotationDetectionFieldCallback.java:89) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.repository.core.support.ReflectionEntityInformation.<init>(ReflectionEntityInformation.java:68) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	... 41 common frames omitted
```

**Comment by derjust** [comment]
The wiki article about this can be found here:
[Use Hash and Range Keys](https://github.com/derjust/spring-data-dynamodb/wiki/Use-Hash-Range-keys)
