### ISSUE TITLE
Spring-data-dynamoDB in Spring Boot app: @DynamoDBTable classes not recognized as persisted entities if @EnableDynamoDBAuditing configured

### ISSUE THREAD

**Issue by cvasilyev** [derjust/spring-data-dynamodb#169]
This issue is originally posted on [stackoverflow](https://stackoverflow.com/questions/50751695/spring-data-dynamodb-in-spring-boot-app-dynamodbtable-classes-not-recognized-a), but I got no responses... So I am posting it here hoping to find the resolution...

I am trying to add support for DynamoDB to an existing Spring Boot/Spring Data JPA application - using **spring-data-dynamodb**. 

 - **Spring Boot** version `1.5.12.RELEASE` 
 - **spring-data-dynamodb** version `4.5.5`
 - ** Java ** version 1.8.x

I want to be able to switch between JPA (Oracle, HSQL) and DynamoDB using mutually exclusive Spring profiles (`jpa` and `dynamodb`.) So I have two profile-specific `@Configuration` classes:

    @Configuration
    @Profile("jpa")
    @EnableJpaRepositories(basePackages = "my.persistence.repositories")
    @EnableJpaAuditing
    public class JpaConfig {
    }

and 

    @Configuration
    @Profile("dynamodb")
    @EnableDynamoDBRepositories(basePackages = "my.persistence.repositories")
    @EnableDynamoDBAuditing
    @EnableAutoConfiguration(exclude = {
        DataSourceTransactionManagerAutoConfiguration.class,
        DataSourceAutoConfiguration.class,
        HibernateJpaAutoConfiguration.class
    })
    public class DynamoDBConfig {

        @Value("${amazon.dynamodb.endpoint}")
        private String amazonDynamoDBEndpoint;

        @Value("${amazon.aws.accesskey}")
        private String amazonAWSAccessKey;

        @Value("${amazon.aws.secretkey}")
        private String amazonAWSSecretKey;

        @Bean
        public AmazonDynamoDB amazonDynamoDB() {
            AmazonDynamoDB amazonDynamoDB = new AmazonDynamoDBClient(amazonAWSCredentials());
            if (!StringUtils.isEmpty(amazonDynamoDBEndpoint)) {
                amazonDynamoDB.setEndpoint(amazonDynamoDBEndpoint);
            }
            return amazonDynamoDB;
        }

The `Application` class is annotated with the single `@Configuration` and `@ComponentScan`.

Note that I am specifically attempting to exclude any JPA auto-configuration when the `dynamodb` profile is activated. 

Also, note that I am hoping to be able to use the *same Spring Data repository interfaces and entity classes*. There is, of course, nothing in the repository interfaces that is specific to JPA or DynamoDB. And I assume that adding DynamoDb annotations to the existing JPA annotations should not hurt anything. So I have entity classes such as the following (an old JPA entity class with *added DynamoDB annotations*):

     @Entity
     @Table(name = "person")
     @DynamoDBTable(tableName = "person")
     @EntityListeners({AuditingEntityListener.class})
     @Getter
     @Setter
     @NoArgsConstructor
     @ToString
     public class Person implements Serializable {
         private static final long serialVersionUID = 1L;

         @Id
         @DynamoDBHashKey
         @DynamoDBAutoGeneratedKey
         private String id;

         @Column(name = "first_name")
         @DynamoDBAttribute
         private String firstName;
    
         @Column(name = "last_name")
         @DynamoDBAttribute
         private String lastName;

         @Column(name = "created_dt", nullable = false)
         @CreatedDate
         @DynamoDBAttribute
         @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
         private Date createdDate;
         
         ... etc.
    }

And the corresponding repository remains unchanged (I've only added the `@EnableScan` annotation, following an example):

     @EnableScan
     public interface PersonRepository extends Repository<Person, String> {

          Person findOne(String id);

          Person save(Person person);
     }

When I run the application with the `jpa` Spring profile activated everything works fine - just as it used to prior to the addition of the DynamoDB support. However, when I launch the application with the `dynamodb` profile, it starts up ok, but the data access operations fail with an exception that indicates that the Person object is **not recognized as a persisted entity**:

     java.lang.IllegalArgumentException: Unsupported entity my.model.Person! Could not determine IsNewStrategy.
	at org.springframework.data.support.IsNewStrategyFactorySupport.getIsNewStrategy(IsNewStrategyFactorySupport.java:48) ~[spring-data-commons-1.13.8.RELEASE.jar:na]
	at org.springframework.data.auditing.IsNewAwareAuditingHandler.markAudited(IsNewAwareAuditingHandler.java:80) ~[spring-data-commons-1.13.8.RELEASE.jar:na]
	at org.socialsignin.spring.data.dynamodb.mapping.event.AuditingEventListener.onBeforeSave(AuditingEventListener.java:44) ~[spring-data-dynamodb-4.5.5.jar:4.5.5]
	at org.socialsignin.spring.data.dynamodb.mapping.event.AbstractDynamoDBEventListener.onApplicationEvent(AbstractDynamoDBEventListener.java:109) ~[spring-data-dynamodb-4.5.5.jar:4.5.5]

When I step through the framework code in the debugger I see that the exception is thrown when the check for the target class being a persisted entity class returns `false`, which, in return, yields a null `IsNewStrategy`. 

The stack trace indicates that this happens during the audit listener execution. If I remove the `EnableDynamoDBAuditing` annotation from my configuration, I seem to get a bit further, but a different exception is thrown:

     Caused by: java.lang.IllegalAccessError: tried to access method com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.getTableModel(Ljava/lang/Class;Lcom/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig;)Lcom/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperTableModel; from class org.socialsignin.spring.data.dynamodb.core.DynamoDBTemplate
	at org.socialsignin.spring.data.dynamodb.core.DynamoDBTemplate.getTableModel(DynamoDBTemplate.java:311) ~[spring-data-dynamodb-4.5.5.jar:4.5.5]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCreator.create(AbstractDynamoDBQueryCreator.java:64) ~[spring-data-dynamodb-4.5.5.jar:4.5.5]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCreator.create(AbstractDynamoDBQueryCreator.java:42) ~[spring-data-dynamodb-4.5.5.jar:4.5.5]
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createCriteria(AbstractQueryCreator.java:109) ~[spring-data-commons-1.13.11.RELEASE.jar:na]
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:88) ~[spring-data-commons-1.13.11.RELEASE.jar:na]
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:73) ~[spring-data-commons-1.13.11.RELEASE.jar:na]
	at org.socialsignin.spring.data.dynamodb.repository.query.PartTreeDynamoDBQuery.doCreateQuery(PartTreeDynamoDBQuery.java:60) ~[spring-data-dynamodb-4.5.5.jar:4.5.5]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery.doCreateQueryWithPermissions(AbstractDynamoDBQuery.java:80) ~[spring-data-dynamodb-4.5.5.jar:4.5.5]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery$SingleEntityExecution.execute(AbstractDynamoDBQuery.java:271) ~[spring-data-dynamodb-4.5.5.jar:4.5.5]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery.execute(AbstractDynamoDBQuery.java:304) ~[spring-data-dynamodb-4.5.5.jar:4.5.5]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:492) ~[spring-data-commons-1.13.11.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:475) ~[spring-data-commons-1.13.11.RELEASE.jar:na]

I see that my JPA functionality is effectively disabled when the `dynamodb` profile is activated. No interference there. My entities package seems to be ignored by Spring Data MongoDB - if MongoDB audit is enabled via `@EnableDynamoDBAuditing`. And, even without that, nothing works due to what appears to be some kind of library mismatch...

Unfortunately, there seems to be no comprehensive documentation for the `spring-data-dynamodb` project, and the examples I have found are too trivial and don't provide any info on the `@EnableDynamoDBRepositories` usage, or any reasonable framework details, for that matter... I don't see anything in the Spring Data DynamoDB project that indicates that any additional configuration might be required other than adding the `@EnableDynamoDBRepositories` annotation.

Would greatly appreciate any help/advice! Many thanks in advance. 

  [1]: https://github.com/derjust/spring-data-dynamodb

**Comment by cvasilyev** [comment]
I have removed the explicit dependency definition for aws-java-sdk-dynamodb, that was sitting in my POM since the original exercise to replicate some online examples, and the IllegalAccessError exception case got resolved - the later lib version that is pulled by spring-data-dynamodb no longer has the method as private. However, I still don't know how to properly enable DynamoDB auditing via the `@EnableDynamoDBAuditing` annotation. If I add that annotation, it seems that the persisted entity class no longer gets recognized as such.

**Comment by derjust** [comment]
The `@EnableDynamoDBAuditing` behavior is for sure the least documented feature.
To have JPA and DynamoDB to co-exist I think you have to have your entity classes in different packages and assign those packages accordingly.
Otherwise Spring-Data has a hard time handling those entities. Example here: https://github.com/derjust/spring-data-dynamodb/wiki/Multi-Repository-configuration

As said, the Auditing was contributed and I have to double-check how it behaves in your scenario

**Comment by ConstantinePP** [comment]
@derjust, Thank you very much for your response. For all it's worth, I think I was able to successfully reuse the model and repository classes - as long as the JPA and DynamoDB profile configurations are _mutually exclusive_. In other words, if I effectively exclude all JPA-related configuration (from Spring Boot auto configuration) when the DynamoDB profile is activated (or vice versa) everything seems to work fine. My application has to be deployed either with a SQL database (Oracle) or DynamoDB, but never with both. So, defining mutually exclusive configuration classes seems to do the trick. So there is no need for multiple model/repository definitions.
