### ISSUE TITLE
Proper way to query GSI by Hash and Range?

### ISSUE THREAD

**Issue by efenderbosch** [derjust/spring-data-dynamodb#172]
Using version 5.0.2.

I've got a compound Hash/Range working for the primary key. How should it be done for GSIs?

Basically, I'm looking to add a `Optional<MyEntity> findByAttributeOneAndAttributeTwo(Object hash, Object range)` method to my repo. The range key should match with `ComparisonOperator.EQ`

Should I use two separate attributes, or does this need to be done similar to the main table, using an object to represent the compound GSI key?

**Comment by derjust** [comment]
No, for GSIs the respective attributes (or getter) need the `@DynamoDBIndexHashKey` and `@DynamoDBIndexRangeKey` annotations & need to specify the GSI name.

I think the integration test `InstallationRepository` is very helpful as an example at
https://github.com/derjust/spring-data-dynamodb/blob/b819234f83210f7b5f186a022565a4859f5091c0/src/test/java/org/socialsignin/spring/data/dynamodb/domain/sample/InstallationRepository.java


On Jun 19, 2018, at 3:55 PM, Eric Fenderbosch <notifications@github.com<mailto:notifications@github.com>> wrote:


I've got a compound Hash/Range working for the primary key. How should it be done for GSIs?

**Comment by efenderbosch** [comment]
That's what I've tried:

Entity attributes:
```java
@DynamoDBIndexHashKey(attributeName = "integration_id", globalSecondaryIndexName = "integration_entity_id_index")
private UUID integrationId;
@DynamoDBIndexRangeKey(attributeName = "entity_id", globalSecondaryIndexName = "integration_entity_id_index")
private String entityId;
```

Repo method:
```java
Optional<Order> findByIntegrationIdAndEntityId(UUID integrationId, String entityId);
```

Stack trace:

```
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at com.amazonaws.services.dynamodbv2.datamodeling.StandardModelFactories$StandardModelFactory.getTableFactory(StandardModelFactories.java:82)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.getTableModel(DynamoDBMapper.java:392)
	at org.socialsignin.spring.data.dynamodb.core.DynamoDBTemplate.getTableModel(DynamoDBTemplate.java:242)
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCreator.create(AbstractDynamoDBQueryCreator.java:63)
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCreator.create(AbstractDynamoDBQueryCreator.java:41)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createCriteria(AbstractQueryCreator.java:119)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:95)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:81)
	at org.socialsignin.spring.data.dynamodb.repository.query.PartTreeDynamoDBQuery.doCreateQuery(PartTreeDynamoDBQuery.java:58)
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery.doCreateQueryWithPermissions(AbstractDynamoDBQuery.java:79)
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery$SingleEntityExecution.execute(AbstractDynamoDBQuery.java:270)
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery.execute(AbstractDynamoDBQuery.java:303)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:590)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy75.findByIntegrationIdAndEntityId(Unknown Source)
```

**Comment by efenderbosch** [comment]
I created a demo project to try to narrow down the problem and it works just fine. However, when I copy the entity and repo from the demo project to the "real" project, it breaks. I'm guessing there's some sort of dependency versioning problem. I'll update more as I figure it out.

**Comment by efenderbosch** [comment]
Figured it out. The test `@Configuration` was doing `return DynamoDBMapperConfig.builder().build()` instead of `return new DynamoDBMapperConfig.Builder().build()`

We fixed it in our non-test `@Configuration` but didn't update the one that uses embedded/local DynamoDB.
