### ISSUE TITLE
Upgrading to 5.1.0 results in the error Bean property 'dynamoDBMapperConfig' is not writable or has an invalid setter method.

### ISSUE THREAD

**Issue by davidmelia** [derjust/spring-data-dynamodb#235]
Hi,

I have recreated this error in https://github.com/davidmelia/spring-data-dynamodb-bug (run the test DynamoDbBugTests)

In a nutshell, after upgrading to 5.1.0 I get the error below:

```
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'dynamoDBMapperConfig' of bean class [org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactoryBean]: Bean property 'dynamoDBMapperConfig' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:243) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.AbstractNestablePropertyAccessor.processLocalProperty(AbstractNestablePropertyAccessor.java:426) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:278) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:266) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:97) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:77) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1681) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	... 55 common frames omitted
```

**Comment by jakobgalbavy** [comment]
I guess, this is related to #230

**Comment by shexbeer** [comment]
Get the same error when updating to 5.1.0 and spring boot 2.1.3
Is this really related to #230 because it does not occur on Tests. It occurs on application run

**Comment by derjust** [comment]
Probably related, yes.
This one is fixed in `master` and will be part of `5.1.1`

**Comment by ghsatpute** [comment]
Hi @derjust any expected date of release of 5.1.1?

**Comment by allan-todd** [comment]
Hi @derjust , I'd also be keen to know when 5.1.1 will be released as we're a bit stuck at the moment.  We had to upgrade from 5.0.4 to fix https://github.com/derjust/spring-data-dynamodb/issues/218 but can't use 5.1.0 owing to this issue.

Thanks

**Comment by shexbeer** [comment]
Regarding #230 and #237 it would be good to have a fix here!

**Comment by lwis** [comment]
Any news on a 5.1.1 release?

**Comment by psabharwal123** [comment]
@derjust ^

**Comment by mpataki** [comment]
I'm starting a new project on boot 2.1.8 and 5.1.0 and hitting this issue. :pray:

**Comment by lmeadows** [comment]
@derjust Is 5.1.1 ready to go? I am considering making my own maven package based on the current state of master in this repo and vendoring it into my app so that I can have this crucial fix. My main concern is that the 5.1.1 release is being held up by quality problems. Is it ready for production?

**Comment by boostchicken** [comment]
@lmeadows 

https://github.com/boostchicken/spring-data-dynamodb

    api  group: 'io.github.boostchicken', name: 'spring-data-dynamodb', version: '5.2.0-SNAPSHOT'

on OSSRH, give it go and let me know if it works and I'll release soon.  Has Spring Boot 2.2 support

**Comment by snakeru** [comment]
Thank you, @boostchicken 

My test compiles and runs now!

**Comment by boostchicken** [comment]
api  group: 'io.github.boostchicken', name: 'spring-data-dynamodb', version: '5.2.1'
On maven central now

**Comment by dlaroue4** [comment]
@boostchicken Thank you!

**Comment by algimantasligeikis** [comment]
> 'io.github.boostchicken

Thank you very much, @boostchicken you are wonderful person :)
