### ISSUE TITLE
Invalid property 'dynamoDBMapperConfig' of bean class [org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactoryBean] - Release 5.1.1

### ISSUE THREAD

**Issue by shexbeer** [derjust/spring-data-dynamodb#253]
Many users still have this issue: (see #230 #237)

```
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'dynamoDBMapperConfig' of bean class [org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactoryBean]: Bean property 'dynamoDBMapperConfig' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:243)
	at org.springframework.beans.AbstractNestablePropertyAccessor.processLocalProperty(AbstractNestablePropertyAccessor.java:426)
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:278)
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:266)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:97)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:77)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1714)
	... 31 common frames omitted
```

I read in your comment in issue #235 (https://github.com/derjust/spring-data-dynamodb/issues/235#issuecomment-471334275_) that its fixed in master and is part of 5.1.1

Please some maintainer, please release 5.1.1 because many of us are blocked and need this fix.
Also see Pullrequest https://github.com/derjust/spring-data-dynamodb/pull/238

------------------------------------------------------------
This one is fixed in `master` and will be part of `5.1.1`

_Originally posted by @derjust in https://github.com/derjust/spring-data-dynamodb/issues/235#issuecomment-471334275_

**Comment by boostchicken** [comment]
https://github.com/derjust/spring-data-dynamodb/wiki/Access-to-releases

Go grab the snapshot, that's what I am running

**Comment by shexbeer** [comment]
Thanks for that hint

**Comment by johnmilimo** [comment]
@boostchicken  I have my Gradle build set with the snapshot URL.

```
repositories {
	mavenCentral()
	maven(url = "https://oss.sonatype.org/content/repositories/snapshots")
}
```

Now my dilemma is how should I define the dependency (version wise )?  I have tried the below but it is not working:

```
dependencies {
        ...
	implementation("com.github.derjust:spring-data-dynamodb:5.1.1-SNAPSHOT")
}
```

Unable to resolve. How is it identified on the snapshots repo?

**Comment by gauravbrills** [comment]
@derjust not sure mine giving a weird error (below) when I start using the snapshot
```


FAILURE: Build failed with an exception.

What went wrong:
java.lang.ArrayIndexOutOfBoundsException (no error message)

```

**Comment by boostchicken** [comment]
api  group: 'io.github.boostchicken', name: 'spring-data-dynamodb', version: '5.2.1'
On maven central now

**Comment by gauravbrills** [comment]
@boostchicken  is the repo transitioning to your repo from now on ? Or will there be a PR on this later .

**Comment by boostchicken** [comment]
I have PRs sent, but I have not heard from derjust lately.  I would like to not fork it but unless we see movement here it might be the best idea

**Comment by ddskolla** [comment]
I have tried @boostchicken's 5.2.1 and that did indeed resolve the issue.
Still don't see a 5.1.1 release on the "derjust/spring-data-dynamodb" project ? Any progress with this ?

**Comment by aauronn** [comment]
I used @boostchicken  5.2.1 and "@Primary" on "dynamoDBMapper" and "dynamoDBMapperConfig" and solved the issue
