### ISSUE TITLE
Getting NPE 

### ISSUE THREAD

**Issue by rimal** [derjust/spring-data-dynamodb#280]
## Expected Behavior
Getting NPE while performing any DynamoDB access.
The request goes through but getting this error constantly.

```
2020-04-28 01:26:34.006  WARN 1045 --- [           main] com.amazonaws.retry.ClockSkewAdjuster    : Unable to parse clock skew offset from response: null

java.lang.NullPointerException: null
	at com.amazonaws.retry.ClockSkewAdjuster.getServerDate(ClockSkewAdjuster.java:180) [aws-java-sdk-core-1.11.769.jar:na]
	at com.amazonaws.retry.ClockSkewAdjuster.updateEstimatedSkew(ClockSkewAdjuster.java:78) [aws-java-sdk-core-1.11.769.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1363) [aws-java-sdk-core-1.11.769.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) [aws-java-sdk-core-1.11.769.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) [aws-java-sdk-core-1.11.769.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) [aws-java-sdk-core-1.11.769.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) [aws-java-sdk-core-1.11.769.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) [aws-java-sdk-core-1.11.769.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) [aws-java-sdk-core-1.11.769.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) [aws-java-sdk-core-1.11.769.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) [aws-java-sdk-core-1.11.769.jar:na]
```

## Steps to Reproduce the Problem

  1. Happens on any request to DynamoDB. I am trying with local DynamoDB.

## Specifications
  
  - Spring Data DynamoDB Version: 5.1.0 (2.1)
  - Spring Data Version: 2.2.6.RELEASE
  - AWS SDK Version: 1.11.769
  - Java Version: 1.8.0_162 - Java HotSpot(TM) 64-Bit Server VM 25.162-b12
  - Platform Details: Mac OS X 10.12.6

**Comment by jwnming** [comment]
hello,i met the same problem as you.
have you solved  this problem?
If so, can you tell me how to solve it

**Comment by allan-todd** [comment]
I'd suggest trying https://github.com/boostchicken/spring-data-dynamodb/
