### ISSUE TITLE
CrudRepository.findOne(Id id) throws NullPointerException instead of IllegalArgumentException when id is null

### ISSUE THREAD

**Issue by fpoolev** [derjust/spring-data-dynamodb#51]
Not a major issue, but we should try and ensure consistency with the online documentation.

http://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#findOne-ID-

**Comment by derjust** [comment]
Agreed. I assumed that was covered with #27 but obv. it isn't

**Comment by derjust** [comment]
if at hand, the stacktrace of the `IllegalArgumentException` would be helpful

**Comment by fpoolev** [comment]
java.lang.NullPointerException
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.springframework.util.ReflectionUtils.getField(ReflectionUtils.java:143)
	at org.socialsignin.spring.data.dynamodb.repository.support.CompositeIdHashAndRangeKeyExtractor.getHashKey(CompositeIdHashAndRangeKeyExtractor.java:44)
	at org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBIdIsHashAndRangeKeyEntityInformationImpl.getHashKey(DynamoDBIdIsHashAndRangeKeyEntityInformationImpl.java:56)
	at org.socialsignin.spring.data.dynamodb.repository.support.SimpleDynamoDBCrudRepository.findOne(SimpleDynamoDBCrudRepository.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:483)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:468)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:440)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy150.findOne(Unknown Source)

**Comment by derjust** [comment]
Oh wow. Thanks.
Would you mind adding your model class (the one with the `@Id` annotation - If you use a composite key please the key class, too)?

**Comment by derjust** [comment]
Fixed as part of `5.0.0`
