### ISSUE TITLE
Investigate Order By DynamoDBIndexRangeKey Support

### ISSUE THREAD

**Issue by fpoolev** [derjust/spring-data-dynamodb#52]
I would like to be able to sort the results of a global secondary index query by the global secondary index range key. Currently, the operation is not supported.

Example query signature in the paging and sorting repository.
```
public List<<DAO Type>> findBy<GSI HashKey>OrderBy<GSI Range>Desc
```
java.lang.UnsupportedOperationException: Sorting only possible by [driverId] for the criteria specified

```
at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCriteria.applySortIfSpecified(AbstractDynamoDBQueryCriteria.java:163)
at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCriteria.buildQueryRequest(AbstractDynamoDBQueryCriteria.java:114)
at org.socialsignin.spring.data.dynamodb.repository.query.DynamoDBEntityWithHashKeyOnlyCriteria.buildFinderQuery(DynamoDBEntityWithHashKeyOnlyCriteria.java:61)
at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCriteria.buildQuery(AbstractDynamoDBQueryCriteria.java:433)
at org.socialsignin.spring.data.dynamodb.repository.query.DynamoDBQueryCreator.complete(DynamoDBQueryCreator.java:33)
at org.socialsignin.spring.data.dynamodb.repository.query.DynamoDBQueryCreator.complete(DynamoDBQueryCreator.java:12)
at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:88)
at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:73)
at org.socialsignin.spring.data.dynamodb.repository.query.PartTreeDynamoDBQuery.doCreateQuery(PartTreeDynamoDBQuery.java:65)
at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery.doCreateQueryWithPermissions(AbstractDynamoDBQuery.java:76)
at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery$CollectionExecution.execute(AbstractDynamoDBQuery.java:98)
at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery.execute(AbstractDynamoDBQuery.java:288)
at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:462)
at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:440)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
at com.sun.proxy.$Proxy151.findByDriverIdOrderByTimestampDesc(Unknown Source)
at <removed repository call here>org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254)
at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
```

**Comment by swathikanury** [comment]
I am experiencing the same problem with version 4.3.1:

Following is my data object:

```
package com.scratch.utils;

import java.io.Serializable;
import java.util.Date;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "Installations")
public class Installation implements Serializable {
	
	@JsonIgnore
	private static final long serialVersionUID = 1L;
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String id;

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "systemIdIndex")	
	private String systemId;
	
	@DynamoDBIndexRangeKey(globalSecondaryIndexName = "systemIdIndex")
	private Date updatedAt;
	
}
```

This is how my repository looks like:
```
package com.scratch.utils;

import org.socialsignin.spring.data.dynamodb.repository.EnableScan;
import org.springframework.data.repository.CrudRepository;

@EnableScan
public interface InstallationRepository extends CrudRepository<Installation, String> {
	
	public Installation findBySystemIdOrderByUpdatedAtDesc(String systemId);
	
}
```

When I call the repository method, I am getting the following exception:
```
java.lang.UnsupportedOperationException: Sorting only possible by [organizationIdSystemIdText] for the criteria specified
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCriteria.applySortIfSpecified(AbstractDynamoDBQueryCriteria.java:163)
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCriteria.buildQueryRequest(AbstractDynamoDBQueryCriteria.java:114)
	at org.socialsignin.spring.data.dynamodb.repository.query.DynamoDBEntityWithHashKeyOnlyCriteria.buildFinderQuery(DynamoDBEntityWithHashKeyOnlyCriteria.java:61)
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCriteria.buildQuery(AbstractDynamoDBQueryCriteria.java:433)
	at org.socialsignin.spring.data.dynamodb.repository.query.DynamoDBQueryCreator.complete(DynamoDBQueryCreator.java:33)
	at org.socialsignin.spring.data.dynamodb.repository.query.DynamoDBQueryCreator.complete(DynamoDBQueryCreator.java:12)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:88)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:73)
	at org.socialsignin.spring.data.dynamodb.repository.query.PartTreeDynamoDBQuery.doCreateQuery(PartTreeDynamoDBQuery.java:65)
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery.doCreateQueryWithPermissions(AbstractDynamoDBQuery.java:76)
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery$SingleEntityExecution.execute(AbstractDynamoDBQuery.java:255)
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery.execute(AbstractDynamoDBQuery.java:288)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:462)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:440)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy102.findBySystemIdOrderByUpdatedAtDesc(Unknown Source)
```

Any help would be appreciated.

**Comment by derjust** [comment]
Thanks for the details. I could reproduce it but don't have a good answer yet - esp. because my projects are using sorting. Investigating

**Comment by ffazzini** [comment]
Hi, I have the same issue too ordering by DESC, does anyone have good updates? :)

**Comment by blx** [comment]
I'm having exactly the same issue.

@derjust Hi! When you have some time, do you think you'd be able to post or outline a sample working configuration that you are using in your projects? Are you successfully using exactly the same kind of setup as described in this thread?

**Comment by derjust** [comment]
I could reproduce it. So I'm a bit confused as I'm using a HASH+RANGE key to get a sorted result in an actual project.
Trying to identify the difference right now.

**Comment by alex-arana** [comment]
I have come across this issue as well. I am new to both DynamoDB and spring-data-dynamodb but decided to have a crack at it this afternoon as I am using it in my current project and this is one of our use cases.

As far as I can tell the issue occurs only when the attempting to sort using a RANGE key attribute on a _global secondary index_ and **not** as part of a _Hash and Range Primary Key_ combination.

I put in a fix in the latest code (4.4.2-SNAPSHOT) and have issued a pull-request to @derjust if only to try and shed more light on the underlying issue. My fix consists of identifying global index range key properties as allowed sort properties in the context of dynamically generated query code.

I've taken the liberty of using the test code above to test my fix.

Btw, thanks for your efforts on this great project!

**Comment by foxware00** [comment]
I have tested @alex-arana fixes on my fork and the seem to be working as expected. Thanks alex

**Comment by derjust** [comment]
Fixed as part of merging the PR.
Special thanks for the unit test!
