### ISSUE TITLE
Using dynamodb with other databases

### ISSUE THREAD

**Issue by zabesto** [derjust/spring-data-dynamodb#58]
Hello, I've got the sample working that connects to DynamoDB now that I understand how to hook it up with the composite primary key. However my real application connects to a mysql database as well and I'm trying to understand how to use both in the same project. I've seen info about using two SQL dbs in the same project (http://stackoverflow.com/questions/30362546/how-to-use-2-or-more-databases-with-spring) but I'm thinking the set up for mixing with DynamoDB is different. Currently in our `application.properties` we have set `spring.datasource.*` for the mysql connection settings. I've added the dynamodb java configuration from the sample but when I run I always get an exception. Any suggestions are welcome.

Thanks,
DJ

```
Caused by: java.sql.SQLException: The url cannot be null
	at java.sql.DriverManager.getConnection(DriverManager.java:649)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:308)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:716)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:648)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:468)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:143)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnectiSourceProxy.java:131)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:382)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:87)
	... 42 common frames omitted
```

**Comment by derjust** [comment]
How does your Config/Bean configuration class look like?

**Comment by zabesto** [comment]
I eventually got it working. Thanks

**Comment by derjust** [comment]
Thanks for the feedback. Would you mind sharing your solution so we can add it to the wiki?
