### ISSUE TITLE
Global Secondary Index throws java.lang.AbstractMethodError ?

### ISSUE THREAD

**Issue by ashikaumanga** [derjust/spring-data-dynamodb#63]
Greetings, 
I had following bean with the repository and it worked fine with PrimaryKey.
I followed GSI example and added GSI  as follows:

```
@DynamoDBTable(tableName="users")
public class User {
	
	private String id;
	private String email;
	private String name;
	private String motto;
	private String pic;
	private Long pnts;
	private String country;
	private String state;
	private Long version;
	private Boolean active;
	private Date created;
	
	@Id
	@DynamoDBHashKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName="idx_email")
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	
	@DynamoDBVersionAttribute
	public Long getVersion() {
		return version;
	}
	public void setVersion(Long version) {
		this.version = version;
	}
	@Override
	public String toString() {
		return "User [id=" + id + ", email=" + email + ", version=" + version + "]";
	}
	
	@DynamoDBAttribute
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@DynamoDBAttribute
	public String getMotto() {
		return motto;
	}
	public void setMotto(String motto) {
		this.motto = motto;
	}
	
	@DynamoDBAttribute
	public String getPic() {
		return pic;
	}
	public void setPic(String pic) {
		this.pic = pic;
	}
	
	@DynamoDBAttribute
	public Long getPnts() {
		return pnts;
	}
	public void setPnts(Long pnts) {
		this.pnts = pnts;
	}
	
	@DynamoDBAttribute
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	
	@DynamoDBAttribute
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	
	@DynamoDBAttribute
	public Date getCreated() {
		return created;
	}
	public void setCreated(Date created) {
		this.created = created;
	}
	public Boolean getActive() {
		return active;
	}
	public void setActive(Boolean active) {
		this.active = active;
	}
	
	
}
```

Repository is as follows ;

```
@EnableScan
public interface UserRepository extends DynamoDBCrudRepository<User, String>{
	public List<User> findByEmail(String email);
}
```

But now during Spring initialisation , it throws the Error 

> Caused by: java.lang.AbstractMethodError: org.socialsignin.spring.data.dynamodb.repository.query.DynamoDBQueryLookupStrategy$CreateIfNotFoundQueryLookupStrategy.resolveQuery(Ljava/lang/reflect/Method;Lorg/springframework/data/repository/core/RepositoryMetadata;Lorg/springframework/data/projection/ProjectionFactory;Lorg/springframework/data/repository/core/NamedQueries;)Lorg/springframework/data/repository/query/RepositoryQuery;
> 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.<init>(RepositoryFactorySupport.java:435) ~[spring-data-commons-1.12.3.RELEASE.jar:na]
> 	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:220) ~[spring-data-commons-1.12.3.RELEASE.jar:na]
> 	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:266) ~[spring-data-commons-1.12.3.RELEASE.jar:na]
> 	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:252) ~[spring-data-commons-1.12.3.RELEASE.jar:na]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
> 	... 29 common frames omitted 

What could be the issue here ?

**Comment by ashikaumanga** [comment]
I updated from version 4.3.1 to 4.4.1 and the issue is not there.
