### ISSUE TITLE
BeanCreationException on application startup with Spring Boot 1.5.1

### ISSUE THREAD

**Issue by dasniko** [derjust/spring-data-dynamodb#70]
When using with Spring Boot 1.5.1.RELEASE (Spring Framework Version 4.3.6), I'm getting the following error/stacktrace on startup:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resultEntryRepository': Could not resolve matching constructor (hint: specify index/type/name arguments for simple parameters to avoid type ambiguities)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:240)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:923)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:804)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:558)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:432)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:395)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:515)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:508)
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1189)
	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:862)
	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:848)
	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:834)
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:788)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
```

It worked well until Spring Boot 1.4.4, after upgrading to 1.5.1 the exception occurs. No other things changed.

For completeness, my repository interface:
```
@EnableScan
public interface ResultEntryRepository extends CrudRepository<ResultEntry, String> {
}
```

**Comment by iferca** [comment]
I have the same problem and discovered (because a team mate was working with other versions). 
By changing the version of **aws-java-sdk-dynamodb** to: 

```
<dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-dynamodb</artifactId>
            <version>1.11.34</version>
</dependency>
```

And also spring data to: 

```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-releasetrain</artifactId>
                <version>Gosling-SR1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
</dependencyManagement>
```

The problem is gone now. Seems to be a support issue between the AWS API and spring data API. 
My team is just starting with DynamoDB and we plan to use spring-data integration so @derjust let me know if there is something we can do to test/help/implement.

**Comment by dasniko** [comment]
Thanks, @iferca 
I can confirm the correct behaviour with added `dependencyManagement` node in `pom.xml`.
It seems to work not only with `Gosling` but also with all `Hopper` releasetrains.
However, when starting to use the `Ingalls` releasetrain, the error occurs.

@derjust 
So, perhaps you should publish a new version of your awesome library for Spring Boot >= 1.5.x !?

**Comment by derjust** [comment]
I just pushed out version `4.5.0` which is compatible with Spring-Boot 1.5 / Spring-Data Ingalls and uses AWS SDK `1.11.93`

**Comment by dasniko** [comment]
After MavenRepo finally has updated - everything looks fine. Thank you very much for your support!
