### ISSUE TITLE
NullPointerException for findAllByOrderByProperty queries

### ISSUE THREAD

**Issue by micw** [derjust/spring-data-dynamodb#96]
I tried to have a query method that finds all entities unfiltered) but ordered. The spring-data syntax for this is `findAllByOrderByProperty()`. Unfortunately this results in a nullpointer exception:

```
java.lang.NullPointerException
	at org.socialsignin.spring.data.dynamodb.repository.query.DynamoDBQueryCreator.complete(DynamoDBQueryCreator.java:30)
	at org.socialsignin.spring.data.dynamodb.repository.query.DynamoDBQueryCreator.complete(DynamoDBQueryCreator.java:12)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:88)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:73)
	at org.socialsignin.spring.data.dynamodb.repository.query.PartTreeDynamoDBQuery.doCreateQuery(PartTreeDynamoDBQuery.java:65)
[...]

Reason:
AbstractQueryCreator.createCriteria(PartTree) returns NULL criteria for this tree because it does not contain any node.
```

**Comment by derjust** [comment]
Ok the issue here is that it has no idea that it should apply the range part of an index (primary or GSI) and thus has nothing to apply the sort part on...
